version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: wellnesshub
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d wellnesshub -h localhost"]
      interval: 5s
      retries: 20


  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      retries: 20

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  wellness-resource-service:
    build: ./services/wellness-resource-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wellnesshub
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_REDIS_HOST: redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8081:8081"

  event-service:
    build: ./services/event-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wellnesshub
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8082:8082"

  goal-tracking-service:
    build: ./services/goal-tracking-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/wellnesshub
      RESOURCES_BASE_URL: http://wellness-resource-service:8081
    depends_on:
      mongo:
        condition: service_healthy
      wellness-resource-service:
        condition: service_started
    ports:
      - "8083:8083"
